config/routes.rb
Rails.application.routes.draw do
  resources :publishes
  get 'publishes/show'
  devise_for :users
  root "publishes#index"
  

end

app/models/access.rb
class Access < ActiveRecord::Base
	has_many :users
end

app/models/publish.rb
class Publish < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :access
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
	def index 
	end
	
	def new
		@access = Access.new
	end
	
	def show
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!
	def index
		@publishes= Publish.all
	end
	def show
		@user = User.find(params[:id])
	end 
end

app/controllers/publishes_controller.rb
class PublishesController < ApplicationController
  before_action :set_publish, only: [:show, :edit, :update, :destroy]

  # GET /publishes
  # GET /publishes.json
  def index
    @publishes = Publish.all
  end

  # GET /publishes/1
  # GET /publishes/1.json
  def show
    @user = Publish.find(params[:id])
  end

  # GET /publishes/new
  def new
    @publish = Publish.new
  end

  # GET /publishes/1/edit
  def edit
  end

  # POST /publishes
  # POST /publishes.json
  def create
    @publish = Publish.new(publish_params)

    respond_to do |format|
      if @publish.save
        format.html { redirect_to @publish, notice: 'Publish was successfully created.' }
        format.json { render :show, status: :created, location: @publish }
      else
        format.html { render :new }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishes/1
  # PATCH/PUT /publishes/1.json
  def update
    respond_to do |format|
      if @publish.update(publish_params)
        format.html { redirect_to @publish, notice: 'Publish was successfully updated.' }
        format.json { render :show, status: :ok, location: @publish }
      else
        format.html { render :edit }
        format.json { render json: @publish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishes/1
  # DELETE /publishes/1.json
  def destroy
    @publish.destroy
    respond_to do |format|
      format.html { redirect_to publishes_url, notice: 'Publish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publish
      @publish = Publish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publish_params
      params.require(:publish).permit(:make, :description, :price)
    end
end

app/helpers/accesses_helper.rb
module AccessesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/publishes_helper.rb
module PublishesHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  
    <div id="accesorios" class="jumbotron">
      <div  class="container">
        <h1>Bienvenido a MotoAccess</h1>
        <p>Publica tu articulo</p>
        <hr>
      </div>
    </div>

    <div id="titles" class="container">
      <div class="row">
        <div class="row">
  
      </div>

      <hr>
  <%= form_for :post do |f| %>
    <p>
      <%= f.label :Marca %><br>
      <%= f.text_field :Marca %>
    </p>

    <p>
      <%= f.label :Precio %><br>
      <%= f.text_area :Precio %>
    </p>

    <p>
      <%= f.label :Descripcion %><br>
      <%= f.text_area :Descripcion %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

      <footer>
        <p>&copy; 2016 BootCamp, Produced by Juan Vargas, Juan Ordoñez y Arturo.</p>
      </footer>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MotoAccess</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/publishes/_form.html.erb
<%= form_for(@publish) do |f| %>
  <% if @publish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publish.errors.count, "error") %> prohibited this publish from being saved:</h2>

      <ul>
      <% @publish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishes/edit.html.erb
<h1>Editing Publish</h1>

<%= render 'form' %>

<%= link_to 'Show', @publish %> |
<%= link_to 'Back', publishes_path %>

app/views/publishes/index.html.erb
<body id="page-top" class="index">

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">MOTOACCESS</a>
            </div>
 <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services">Texto falso</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#portfolio">Texto falso</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Texto falso</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Texto falso</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container">
     
            <div class="intro-text">
            <%=image_tag "logoM.png" %>
                <div class="intro-lead-in">Bienvenido a MotoAccess</div>
                <div class="intro-heading">Especially for ridders</div>
                <a href="#services" class="page-scroll btn btn-xl">Texto falso</a>
            </div>
        </div>
    </header>

  
 








<!--<div class="container-fluid">
  
    <div id="accesorios" class="jumbotron">
      <div  class="container">
        <h1>Bienvenido a MotoAccess</h1>
        <p>Especially for ridders</p>
        <hr>
      </div>
    </div>-->
<!-- About Section -->
    <section id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">PASOS PARA PUBLICAR UN PRODUCTO</h2>
                    <h3 class="section-subheading text-muted">(y lograr venderlo).</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="timeline">
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/1.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>1</h4>
                                    <h4 class="subheading">Entra a nuestra web!</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">texto falso</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/2.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>2</h4>
                                    <h4 class="subheading">Ingresa tus datos!</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">texto falso</p>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/3.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>3</h4>
                                    <h4 class="subheading">Ingresa el elemento a vender</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">texto falso</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <img class="img-circle img-responsive" src="img/about/4.jpg" alt="">
                            </div>
                            <div class="timeline-panel">
                                <div class="timeline-heading">
                                    <h4>4</h4>
                                    <h4 class="subheading">Vendela!</h4>
                                </div>
                                <div class="timeline-body">
                                    <p class="text-muted">texto falso</p>
                                </div>
                            </div>
                        </li>
                        <li class="timeline-inverted">
                            <div class="timeline-image">
                                <h4>Be Part
                                    <br>Of Our
                                    <br>project!</h4>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <div id="titles" class="container">
        <div class="row">
        <div class="row">
    
        </div>
    </div>
      <hr>
<p id="notice"><%= notice %></p>
<div class="container col-lg-12 text-center">
<h1>Pública tu articulo</h1>
 
 <div class="page-scroll btn btn btn-xl ">
    <%= link_to 'New Publish', new_publish_path %>
  </div>

  <div class="page-scroll btn btn-xl">
  <%= link_to 'Destroy', destroy_user_session_path, method: :delete %>
  </div>
</div>

<div class="container">
  <p></p>
  <table class="table">
    <thead>
      <tr>
        <th>Make</th>
        <th>Description</th>
        <th>Price</th>
        <!--<th colspan="3"></th>-->
      </tr>
    </thead>
    <tbody>
    <% @publishes.each do |publish| %>
      <tr>
        <td><%= publish.make %></td>
        <td><%= publish.description %></td>
        <td><%= publish.price %></td>
      </tr>
      <div class="container col-lg-12 text-center">
      <tr>
        <td class="page-scroll btn btn btn-xm "><%= link_to 'Show', publish %></td>
    
        <td class="page-scroll btn btn btn-xm "><%= link_to 'Edit', edit_publish_path(publish) %></td>
        
        <td class="page-scroll btn btn btn-xm "><%= link_to 'Destroy', publish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </div>
        <% end %>
    </tbody>
  </table>
</div>




<!--<table>
  <thead>
    <tr>
      <th>Make</th> <br>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishes.each do |publish| %>
      <tr>
        <td><%= publish.make %></td>
        <td><%= publish.description %></td>
        <td><%= publish.price %></td>
        <td><%= link_to 'Show', publish %></td>
        <td><%= link_to 'Edit', edit_publish_path(publish) %></td>
        <td><%= link_to 'Destroy', publish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>-->

<br>
 
 

 
  <br><br><br><br><br><br><br><br><br><br><br><br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>


        <footer>
          <p>&copy; 2016 BootCamp, Produced by Juan Vargas, Juan Ordoñez y Arturo.</p>
        </footer>

        
    
</div>

app/views/publishes/new.html.erb
<h1>New Publish</h1>

<%= render 'form' %>

<%= link_to 'Back', publishes_path %>

app/views/publishes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Make:</strong>
  <%= @publish.make %>
</p>

<p>
  <strong>Description:</strong>
  <%= @publish.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @publish.price %>
</p>

<%= link_to 'Edit', edit_publish_path(@publish) %> |
<%= link_to 'Back', publishes_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>